language: rust
sudo: false
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
install:
- curl https://nodejs.org/dist/v0.12.7/node-v0.12.7-sunos-x64.tar.gz > node.tar.gz
- tar xf node.tar.gz
- export PATH=$PATH:$pwd/node-v0.12.7-linux-x64/bin
script:
- rustc --version
- make
- make test
- make html
notifications:
  email:
  - shaposhnikigor95@bk.ru
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
branches:
  only: master
env:
  global:
  - secure: FJdPxXSqt05UPmXlnhAJ7bQ6YnUDlS3eH00iTbV/i7j3UXtxGTPKj+uJVob/YP/LnhHwQdMjyiXNpz69GESFMUWVWGOJRsdOcyjRPdy6ZoOldz4L0K6lCYNx7F5I5vemUOK5nbh6nU16dxhKITwHQvC2hhl9mDXMjEqzYD+gyNCW7YstzEv+bfnOoyh3daAlXCgiJaWE1gltrT24GtVq7ZfL30VHEl161UuVTmJSmGahKThuEuhV8j0Fr7WYkImAgN2hHuZBRfBrFDjMo+eQ6hN4dQy6f+GkAIfK6BLj1NlElpF/uqynvuMbN5KDA4ygnDcncDU1n5JskpDIawhkOerKmBjXWTG/EH1ZUZqPjowXYthlvSOMmS/xp+Ux+4YPdOlp3gPbmmc81osPu//yZ6B4FgY/dzLv1tx+Aj9gGVc4Z5JJVY2zJmomYiJXq/tr1n5g6+NCfFLBZpex0HlKEGl1E4nhZQYzOSdusq8Q5sC46WC0mMYslRf36y65k9zIhLHg/23b7kmmGVHWxPeOivQR/Uujoy0KenSo9Ldji6a9aSmbdrmAy+KM9744BlRLQQREzQ0zraFA/CVGLyzAWbr7FZ8J3wg4EJBIi0gDgfQnJaE7ruQBwVFl7TKDr5dWYEx7ZNIxojd0VPKGkBjTGOuJ7J96MQf0JLpZh0w2VNg=
